### ISSUE TITLE
 no such file or directory, open 'XYZ\out\development\main.lua

### ISSUE THREAD

**Issue by tiramon** [wolfe-labs/DU-LuaC#3]
If you set up a new project like described in the readme

du-lua create XYZ
du-lua script-add main
du-lua script-link main
du-lua target-add
du-lua build

the build crashs with 
```
Lua CLI Utility for Dual Universe v0.6.0 by Wolfe Labs @ Node v14.17.0
No Lua tools found on your system. This will not affect builds.
You can download the binaries at: http://luabinaries.sourceforge.net/

Loading project file: XYZ\project.json
Loading project library: "XYZ"

Compiling build "main"...
Fetching project entry point: main
-> Building file: XYZ\src\main.lua
Building LUA AST and checking for syntax errors...
-> No syntax errors found!
Generating build files for target "development"...
-> Writing Lua output...
(node:71952) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'XYZ\out\development\main.lua'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1524:35)
    at C:\Users\USER\AppData\Roaming\npm\node_modules\@wolfe-labs\du-luac\build.js:181:10
    at Array.map (<anonymous>)
    at C:\Users\USER\AppData\Roaming\npm\node_modules\@wolfe-labs\du-luac\build.js:161:100
    at Array.map (<anonymous>)
    at module.exports (C:\Users\USER\AppData\Roaming\npm\node_modules\@wolfe-labs\du-luac\build.js:138:95)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:71952) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:71952) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Problem is that the out/development folder is not created automatically
If the folders are created manually it build just fine

**Comment by tiramon** [comment]
this is general true for all calls of target-add, you just need a mkdir in the target-add call

**Comment by tiramon** [comment]
or even better with the build call, because else a simple checkout and build on another system will get the same error

**Comment by matpratta** [comment]
Hey @tiramon, please check https://github.com/wolfe-labs/DU-LuaC/releases/tag/0.6.1 as it should fix this issue! Thanks for reporting! :)
