### ISSUE TITLE
import github library

### ISSUE THREAD

**Issue by tiramon** [wolfe-labs/DU-LuaC#6]
You wrote that importing a library with the git https clone url should work ...
Or is it a must that the imported lib is a du-lua project?

```
$ du-lua import https://github.com/EasternGamer/AR-Library.git
Lua CLI Utility for Dual Universe v0.6.3 by Wolfe Labs @ Node v10.16.0
Downloading library files from: "https://github.com/EasternGamer/AR-Library.git"
(node:324) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:427:7)
    at Function.getProjectInfo (C:\Users\tiramon\AppData\Roaming\npm\node_modules\@wolfe-labs\du-luac\library.js:178:53)
    at Function.loadExternalLibrary (C:\Users\tiramon\AppData\Roaming\npm\node_modules\@wolfe-labs\du-luac\library.js:142:37)
(node:324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not 
handled with .catch(). (rejection id: 2)
(node:324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.   
```

**Comment by tiramon** [comment]
Ok just found out while reading the code that this is the passage that should tell me that target lib does not have a project.json ... maybe you want to fix that ;)

**Comment by matpratta** [comment]
Fixed the typo, at last!
