### ISSUE TITLE
Install on Windows fail

### ISSUE THREAD

**Issue by tiramon** [wolfe-labs/DU-LuaC#9]
Not sure if it is a problem with upgraded dependencies or with my local system 

`npm i -g @wolfe-labs/du-luac
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path C:\Users\tiramon\AppData\Roaming\npm\node_modules\@wolfe-labs\du-luac\node_modules\nodegit
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! [nodegit] Running pre-install script
npm ERR! [nodegit] Running install script
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\tiramon\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\tiramon\AppData\Roaming\npm\node_modules\@wolfe-labs\du-luac\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\tiramon\AppData\Roaming\npm\node_modules\@wolfe-labs\du-luac\node_modules\nodegit\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp
npm ERR! info it worked if it ends with ok
npm ERR! node-pre-gyp
npm ERR! info using node-pre-gyp@0.13.0
npm ERR! node-pre-gyp
npm ERR! info using node@16.13.0 | win32 | x64
npm ERR! node-pre-gyp WARN
npm ERR! Using request for node-pre-gyp https download
npm ERR! node-pre-gyp
npm ERR! info check checked for "C:\Users\tiramon\AppData\Roaming\npm\node_modules\@wolfe-labs\du-luac\node_modules\nodegit\build\Release\nodegit.node" (not found)
npm ERR! node-pre-gyp
npm ERR! http GET https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-win32-x64.tar.gz
npm ERR! node-pre-gyp
npm ERR! http 404 https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-win32-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-win32-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not found for nodegit@0.27.0 and node@16.13.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp http 404 status code downloading tarball https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-win32-x64.tar.gz
npm ERR! gyp
npm ERR!
npm ERR! info it worked if it ends with ok
npm ERR! gyp
npm ERR! info using node-gyp@8.3.0
npm ERR! gyp
npm ERR! info
npm ERR! using node@16.13.0 | win32 | x64
npm ERR! gyp
npm ERR! info
npm ERR! ok
npm ERR! gyp
npm ERR!
npm ERR! info it worked if it ends with ok
npm ERR! gyp
npm ERR! info using
npm ERR! node-gyp@8.3.0
npm ERR! gyp
npm ERR! info using node@16.13.0 | win32 | x64
npm ERR! gyp
npm ERR! info find Python using Python version 3.10.0 found at "C:\Users\tiramon\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp
npm ERR! ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more detailsnpm ERR! gyp ERR!
npm ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp
npm ERR! ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp
npm ERR! ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR!
npm ERR! find VS
npm ERR! gyp
npm ERR! ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\tiramon\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp
npm ERR! ERR! stack     at C:\Users\tiramon\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\tiramon\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\Users\tiramon\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14      
npm ERR! gyp ERR!
npm ERR! stack     at C:\Users\tiramon\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\Users\tiramon\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\tiramon\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp
npm ERR! ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack
npm ERR! at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\tiramon\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\tiramon\\AppData\\Roaming\\npm\\node_modules\\@wolfe-labs\\du-luac\\node_modules\\nodegit\\build\\Release\\nodegit.node" "--module_name=nodegit" "--module_path=C:\\Users\\tiramon\\AppData\\Roaming\\npm\\node_modules\\@wolfe-labs\\du-luac\\node_modules\\nodegit\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd C:\Users\tiramon\AppData\Roaming\npm\node_modules\@wolfe-labs\du-luac\node_modules\nodegit
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack
npm ERR! Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\tiramon\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --mod\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\tiramon\AppData\Roaming\npm\node_modules\@wolfe-labs\du-luac\node_modules\node --module_path=C:\Users\tiramon\AppData\Roaming\npm\git\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\tiramon\AppData\Roaming\npm\node_modules\@wolfe-labs\du-luac\node_mbel=node-v93' (1)odules\nodegit\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)                      dules\node-pre-gyp\lib\util\compile.js:83:29)       
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\tiramon\AppData\Roaming\npm\node_modules\@wolfe-labs\du-luac\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System                                                                                                              \du-luac\\node_modules\\node-pre-gyp\\bin\\node-pre-
npm ERR! Windows_NT 10.0.19042
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\tiramon\\AppData\\Roaming\\npm\\node_modules\\@wolfe-labs\\du-luac\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\tiramon\AppData\Roaming\npm\node_modules\@wolfe-labs\du-luac\node_modules\nodegit
npm ERR! node-pre-gyp ERR! node -v v16.13.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.13.0
npm ERR! node-pre-gyp ERR! not ok
npm ERR! [nodegit] ERROR - Could not finish install
npm ERR! [nodegit] ERROR - finished with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tiramon\AppData\Local\npm-cache\_logs\2021-11-29T13_58_20_349Z-debug.log`

**Comment by tiramon** [comment]
ok install 6.8GB (VS including the "Desktop development with C++" workload.) and it works ...
